import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { clientAssurance } from "@/lib/clients/assurance";

export function ClientAssuranceDepth() {
  return (
    <div className="grid gap-6 xl:grid-cols-2">
      <Card><CardHeader><div><CardTitle>Setting-aware legal authorisation</CardTitle><CardDescription>Capacity, best-interest decisions, restrictions and authorisation are separate records.</CardDescription></div><Badge tone="success">{clientAssurance.authorisation.status}</Badge></CardHeader><CardContent><dl className="space-y-3 text-sm">{Object.entries(clientAssurance.authorisation).map(([label, value]) => <div key={label} className="grid gap-1 sm:grid-cols-[150px_1fr]"><dt className="font-semibold capitalize">{label.replaceAll(/([A-Z])/g, " $1")}</dt><dd className="text-slate-600">{value}</dd></div>)}</dl></CardContent></Card>
      <Card><CardHeader><div><CardTitle>Structured restrictive-practice review</CardTitle><CardDescription>Keyword candidates remain indicators until human classification.</CardDescription></div><Badge tone="warning">est. indicator</Badge></CardHeader><CardContent><dl className="space-y-3 text-sm">{Object.entries(clientAssurance.restrictivePractice).map(([label, value]) => <div key={label} className="grid gap-1 sm:grid-cols-[130px_1fr]"><dt className="font-semibold capitalize">{label.replaceAll(/([A-Z])/g, " $1")}</dt><dd className="text-slate-600">{value}</dd></div>)}</dl></CardContent></Card>
      <Card><CardHeader><div><CardTitle>Competency-to-need matching</CardTitle><CardDescription>Expired records never count; absent requirements produce Unknown.</CardDescription></div></CardHeader><CardContent className="space-y-3">{clientAssurance.competencies.map((item) => <div key={item.requirement} className="flex flex-col justify-between gap-2 rounded-xl border border-slate-200 p-3 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold">{item.requirement}</p><p className="text-xs text-slate-500">{item.caregiver} · expires {item.expires}</p></div><Badge tone={item.status === "Current" ? "success" : item.status === "Gap" ? "danger" : "warning"}>{item.status}</Badge></div>)}</CardContent></Card>
      <Card><CardHeader><div><CardTitle>Outcomes, risks and observations</CardTitle><CardDescription>AI summarises recorded progress but never infers an unrecorded outcome.</CardDescription></div></CardHeader><CardContent><p className="font-semibold">{clientAssurance.carePlan.goal}</p><p className="mt-2 text-sm leading-6 text-slate-600">{clientAssurance.carePlan.progress}</p><p className="mt-3 text-xs text-slate-500">Risk review {clientAssurance.carePlan.riskReview} · owner {clientAssurance.carePlan.owner}</p><div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm"><strong>Filtered note export:</strong> {clientAssurance.observationExport.filteredRows} · {clientAssurance.observationExport.rowCap} · {clientAssurance.observationExport.formats.join(" / ")}</div></CardContent></Card>
    </div>
  );
}
