export const clientAssurance = {
  authorisation: {
    setting: "Supported living",
    availableRoute: "Community / Court of Protection authorisation",
    excludedRoute: "DoLS is not available for this setting",
    capacityAssessment: "Recorded 04 Jun 2026",
    bestInterestDecision: "Reviewed 06 Jun 2026",
    restrictions: "Night-time door support; least-restrictive review recorded",
    status: "Active",
    expiry: "19 Aug 2026",
    renewalAction: "ACT-188 raised at T-30",
    document: "AUTH-72 · short-lived document link",
  },
  restrictivePractice: {
    id: "RPI-41",
    type: "Physical intervention candidate",
    trigger: "Environmental distress",
    duration: "2 minutes",
    technique: "Approved low-arousal support",
    injury: "None recorded",
    deescalation: "Quiet space and familiar staff",
    debrief: "Missing — action ACT-211 raised",
    outcome: "Calm recorded after 9 minutes",
    label: "AI-derived impact read · human review required",
  },
  competencies: [
    { requirement: "Epilepsy awareness", caregiver: "Staff S-018", expires: "12 Dec 2026", status: "Current" },
    { requirement: "Medication level 2", caregiver: "Staff S-024", expires: "03 Aug 2026", status: "Due soon" },
    { requirement: "PBS plan", caregiver: "Unallocated", expires: "Unknown", status: "Gap" },
  ],
  carePlan: {
    goal: "Choose and prepare one evening meal each week",
    baseline: "Supported choice recorded",
    target: "Independent choice with prompts",
    progress: "Two recorded observations linked; no inferred outcome",
    riskReview: "Due in 18 days",
    owner: "Team Leader",
  },
  observationExport: {
    query: "meal planning",
    filteredRows: "12 of 12",
    rowCap: "No row cap",
    formats: ["CSV", "XLSX", "PDF", "DOCX"],
  },
};
